In [ ]:
import pandas as pd
import numpy as np
from feature_engineering import FeatureEngineering

In [2]:
df = pd.read_csv("clinic_visits.csv")
df

           Patient        Date  Day Visit Time
0          Sneha K  2026-07-01  Wed    8:13 AM
1          Vijay N  2026-07-01  Wed    9:01 AM
2          Sneha V  2026-07-01  Wed    9:01 AM
3      Sanjay Nair  2026-07-01  Wed    9:29 AM
4     Lakshmi Babu  2026-07-01  Wed    9:39 AM
...            ...         ...  ...        ...
1332      Suresh M  2026-08-29  Sat    5:38 PM
1333  Lakshmi Nair  2026-08-29  Sat    5:44 PM
1334  Kiran Nathan  2026-08-29  Sat    6:08 PM
1335      Vikram P  2026-08-29  Sat    7:05 PM
1336       Rahul K  2026-08-29  Sat    8:36 PM

[1337 rows x 4 columns]

In [3]:
df['visit_dt'] = pd.to_datetime(
    df['Date'] + ' ' + df['Visit Time'],
    format='%Y-%m-%d %I:%M %p'
)

df['hour_slot'] = df['visit_dt'].dt.floor('h')

hourly_df = (df.groupby('hour_slot').size().reset_index(name='visit_count'))

In [4]:
hourly_df['Date'] = (
    hourly_df['hour_slot']
    .dt.strftime('%Y-%m-%d')
)

hourly_df['Visit Time'] = (
    hourly_df['hour_slot']
    .dt.strftime('%I:%M %p')
)

In [5]:
X = hourly_df[['Date','Visit Time']]
y = hourly_df['visit_count']

In [6]:
hourly_df = (hourly_df.sort_values('hour_slot').reset_index(drop=True))

In [7]:
hourly_df

              hour_slot  visit_count        Date Visit Time
0   2026-07-01 08:00:00            1  2026-07-01   08:00 AM
1   2026-07-01 09:00:00            4  2026-07-01   09:00 AM
2   2026-07-01 10:00:00            4  2026-07-01   10:00 AM
3   2026-07-01 17:00:00            4  2026-07-01   05:00 PM
4   2026-07-01 18:00:00            4  2026-07-01   06:00 PM
..                  ...          ...         ...        ...
413 2026-08-29 10:00:00            6  2026-08-29   10:00 AM
414 2026-08-29 17:00:00            3  2026-08-29   05:00 PM
415 2026-08-29 18:00:00            1  2026-08-29   06:00 PM
416 2026-08-29 19:00:00            1  2026-08-29   07:00 PM
417 2026-08-29 20:00:00            1  2026-08-29   08:00 PM

[418 rows x 4 columns]

In [10]:
split_idx = int(len(hourly_df) * 0.8)
train_df = (hourly_df.iloc[:split_idx])
test_df = (hourly_df.iloc[split_idx:])

In [11]:
train_df

              hour_slot  visit_count        Date Visit Time
0   2026-07-01 08:00:00            1  2026-07-01   08:00 AM
1   2026-07-01 09:00:00            4  2026-07-01   09:00 AM
2   2026-07-01 10:00:00            4  2026-07-01   10:00 AM
3   2026-07-01 17:00:00            4  2026-07-01   05:00 PM
4   2026-07-01 18:00:00            4  2026-07-01   06:00 PM
..                  ...          ...         ...        ...
329 2026-08-17 09:00:00            5  2026-08-17   09:00 AM
330 2026-08-17 10:00:00            4  2026-08-17   10:00 AM
331 2026-08-17 17:00:00            4  2026-08-17   05:00 PM
332 2026-08-17 18:00:00            3  2026-08-17   06:00 PM
333 2026-08-17 19:00:00            3  2026-08-17   07:00 PM

[334 rows x 4 columns]

In [12]:
X_train = train_df[['Date','Visit Time']]

y_train = train_df['visit_count']

X_test = test_df[['Date','Visit Time']]

y_test = test_df['visit_count']

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [14]:
preprocessor = (ColumnTransformer(transformers=[
            ('session',OneHotEncoder(handle_unknown='ignore'),['session'])],
        remainder='passthrough'))

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

In [16]:
pipe_rf = Pipeline([
    ('FeatureEngineering', FeatureEngineering()),
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(
        n_estimators=100,
        random_state=42
    ))
])

In [17]:
pipe_rf.fit(X_train, y_train)
y_pred = pipe_rf.predict(X_test)
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

In [18]:
print(r2)
print(mse)

0.6147600394410349
0.8353417512120418

In [325]:
import xgboost
from xgboost import XGBRegressor
pipe_xgb = Pipeline([
    ('FeatureEngineering', FeatureEngineering()),
    ('preprocessor', preprocessor),
    ('model', XGBRegressor(
        n_estimators=100,
        random_state=42
    ))
])
pipe_xgb.fit(X_train, y_train)
y_pred = pipe_xgb.predict(X_test)
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print(r2)
print(mse)

0.6189101934432983
0.8263427019119263

In [326]:
from catboost import CatBoostRegressor
pipe_cat = Pipeline([
    ('FeatureEngineering', FeatureEngineering()),
    ('preprocessor', preprocessor),
    ('model', CatBoostRegressor())
])
pipe_cat.fit(X_train, y_train)
y_pred = pipe_cat.predict(X_test)
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print(r2)
print(mse)

Learning rate set to 0.03443
0:	learn: 1.3898483	total: 2.23ms	remaining: 2.23s
1:	learn: 1.3587742	total: 4.04ms	remaining: 2.02s
2:	learn: 1.3289140	total: 5.91ms	remaining: 1.96s
3:	learn: 1.3007159	total: 8.3ms	remaining: 2.06s
4:	learn: 1.2776694	total: 9.98ms	remaining: 1.99s
5:	learn: 1.2536981	total: 12ms	remaining: 1.99s
6:	learn: 1.2278788	total: 13.5ms	remaining: 1.92s
7:	learn: 1.2085638	total: 14.8ms	remaining: 1.84s
8:	learn: 1.1852394	total: 16.7ms	remaining: 1.84s
9:	learn: 1.1624029	total: 18.4ms	remaining: 1.82s
10:	learn: 1.1407182	total: 20.2ms	remaining: 1.82s
11:	learn: 1.1197767	total: 21.8ms	remaining: 1.79s
12:	learn: 1.1042046	total: 23.3ms	remaining: 1.77s
13:	learn: 1.0896237	total: 24.5ms	remaining: 1.73s
14:	learn: 1.0705689	total: 26.1ms	remaining: 1.71s
15:	learn: 1.0524109	total: 27.7ms	remaining: 1.71s
16:	learn: 1.0354331	total: 30.1ms	remaining: 1.74s
17:	learn: 1.0194202	total: 32.4ms	remaining: 1.77s
18:	learn: 1.0078329	total: 33.8ms	remaining: 1.75s
19:	learn: 0.9930827	total: 35.9ms	remaining: 1.76s
20:	learn: 0.9786929	total: 37.4ms	remaining: 1.75s
21:	learn: 0.9689540	total: 38.5ms	remaining: 1.71s
22:	learn: 0.9554668	total: 40.1ms	remaining: 1.7s
23:	learn: 0.9456352	total: 42.1ms	remaining: 1.71s
24:	learn: 0.9341210	total: 43.8ms	remaining: 1.71s
25:	learn: 0.9231182	total: 46.2ms	remaining: 1.73s
26:	learn: 0.9153604	total: 48.2ms	remaining: 1.74s
27:	learn: 0.9046375	total: 50ms	remaining: 1.74s
28:	learn: 0.8969343	total: 52.2ms	remaining: 1.75s
29:	learn: 0.8872467	total: 54.4ms	remaining: 1.76s
30:	learn: 0.8779797	total: 56ms	remaining: 1.75s
31:	learn: 0.8689395	total: 58.2ms	remaining: 1.76s
32:	learn: 0.8603807	total: 60.9ms	remaining: 1.78s
33:	learn: 0.8524846	total: 63.1ms	remaining: 1.79s
34:	learn: 0.8450307	total: 64.8ms	remaining: 1.79s
35:	learn: 0.8378234	total: 66.7ms	remaining: 1.79s
36:	learn: 0.8342780	total: 67.8ms	remaining: 1.76s
37:	learn: 0.8287349	total: 69.8ms	remaining: 1.77s
38:	learn: 0.8236318	total: 71.6ms	remaining: 1.76s
39:	learn: 0.8195598	total: 73ms	remaining: 1.75s
40:	learn: 0.8141294	total: 75.3ms	remaining: 1.76s
41:	learn: 0.8087609	total: 77.2ms	remaining: 1.76s
42:	learn: 0.8073684	total: 78.7ms	remaining: 1.75s
43:	learn: 0.8019813	total: 80.9ms	remaining: 1.76s
44:	learn: 0.7983010	total: 82.7ms	remaining: 1.75s
45:	learn: 0.7944960	total: 84.5ms	remaining: 1.75s
46:	learn: 0.7917681	total: 86.1ms	remaining: 1.74s
47:	learn: 0.7885906	total: 89.1ms	remaining: 1.77s
48:	learn: 0.7869087	total: 89.8ms	remaining: 1.74s
49:	learn: 0.7849612	total: 90.5ms	remaining: 1.72s
50:	learn: 0.7804234	total: 91.4ms	remaining: 1.7s
51:	learn: 0.7768854	total: 92.5ms	remaining: 1.69s
52:	learn: 0.7743348	total: 93.2ms	remaining: 1.67s
53:	learn: 0.7717462	total: 94.2ms	remaining: 1.65s
54:	learn: 0.7692220	total: 95.1ms	remaining: 1.63s
55:	learn: 0.7667428	total: 96.2ms	remaining: 1.62s
56:	learn: 0.7652080	total: 97.5ms	remaining: 1.61s
57:	learn: 0.7638025	total: 98.5ms	remaining: 1.6s
58:	learn: 0.7607816	total: 101ms	remaining: 1.61s
59:	learn: 0.7579755	total: 102ms	remaining: 1.6s
60:	learn: 0.7560533	total: 103ms	remaining: 1.59s
61:	learn: 0.7542294	total: 105ms	remaining: 1.58s
62:	learn: 0.7526817	total: 105ms	remaining: 1.56s
63:	learn: 0.7521744	total: 106ms	remaining: 1.55s
64:	learn: 0.7498935	total: 107ms	remaining: 1.54s
65:	learn: 0.7476689	total: 108ms	remaining: 1.53s
66:	learn: 0.7460889	total: 109ms	remaining: 1.52s
67:	learn: 0.7445615	total: 110ms	remaining: 1.5s
68:	learn: 0.7424277	total: 111ms	remaining: 1.49s
69:	learn: 0.7409438	total: 112ms	remaining: 1.49s
70:	learn: 0.7397442	total: 114ms	remaining: 1.5s
71:	learn: 0.7389919	total: 116ms	remaining: 1.49s
72:	learn: 0.7387610	total: 117ms	remaining: 1.48s
73:	learn: 0.7377150	total: 118ms	remaining: 1.48s
74:	learn: 0.7367225	total: 119ms	remaining: 1.47s
75:	learn: 0.7366374	total: 120ms	remaining: 1.46s
76:	learn: 0.7356059	total: 121ms	remaining: 1.45s
77:	learn: 0.7344972	total: 123ms	remaining: 1.45s
78:	learn: 0.7331611	total: 124ms	remaining: 1.44s
79:	learn: 0.7317390	total: 125ms	remaining: 1.44s
80:	learn: 0.7306074	total: 128ms	remaining: 1.45s
81:	learn: 0.7291920	total: 130ms	remaining: 1.45s
82:	learn: 0.7278155	total: 132ms	remaining: 1.46s
83:	learn: 0.7268380	total: 134ms	remaining: 1.46s
84:	learn: 0.7259741	total: 135ms	remaining: 1.45s
85:	learn: 0.7256900	total: 135ms	remaining: 1.44s
86:	learn: 0.7243890	total: 136ms	remaining: 1.43s
87:	learn: 0.7241366	total: 137ms	remaining: 1.42s
88:	learn: 0.7232854	total: 138ms	remaining: 1.41s
89:	learn: 0.7226939	total: 139ms	remaining: 1.41s
90:	learn: 0.7224747	total: 140ms	remaining: 1.4s
91:	learn: 0.7218234	total: 141ms	remaining: 1.39s
92:	learn: 0.7217207	total: 141ms	remaining: 1.38s
93:	learn: 0.7212430	total: 142ms	remaining: 1.37s
94:	learn: 0.7209439	total: 143ms	remaining: 1.36s
95:	learn: 0.7206789	total: 143ms	remaining: 1.35s
96:	learn: 0.7202240	total: 145ms	remaining: 1.34s
97:	learn: 0.7189309	total: 145ms	remaining: 1.34s
98:	learn: 0.7182507	total: 146ms	remaining: 1.33s
99:	learn: 0.7177485	total: 147ms	remaining: 1.32s
100:	learn: 0.7175305	total: 148ms	remaining: 1.32s
101:	learn: 0.7174857	total: 149ms	remaining: 1.31s
102:	learn: 0.7174438	total: 149ms	remaining: 1.3s
103:	learn: 0.7170560	total: 150ms	remaining: 1.29s
104:	learn: 0.7167944	total: 151ms	remaining: 1.29s
105:	learn: 0.7159805	total: 154ms	remaining: 1.29s
106:	learn: 0.7154710	total: 156ms	remaining: 1.3s
107:	learn: 0.7150876	total: 157ms	remaining: 1.3s
108:	learn: 0.7145521	total: 158ms	remaining: 1.29s
109:	learn: 0.7144004	total: 159ms	remaining: 1.28s
110:	learn: 0.7134990	total: 160ms	remaining: 1.28s
111:	learn: 0.7132214	total: 161ms	remaining: 1.27s
112:	learn: 0.7124883	total: 162ms	remaining: 1.27s
113:	learn: 0.7121293	total: 163ms	remaining: 1.27s
114:	learn: 0.7113247	total: 165ms	remaining: 1.27s
115:	learn: 0.7107843	total: 166ms	remaining: 1.26s
116:	learn: 0.7102336	total: 167ms	remaining: 1.26s
117:	learn: 0.7097107	total: 168ms	remaining: 1.25s
118:	learn: 0.7095002	total: 169ms	remaining: 1.25s
119:	learn: 0.7089248	total: 170ms	remaining: 1.25s
120:	learn: 0.7087777	total: 171ms	remaining: 1.24s
121:	learn: 0.7083000	total: 172ms	remaining: 1.24s
122:	learn: 0.7080431	total: 173ms	remaining: 1.23s
123:	learn: 0.7073539	total: 174ms	remaining: 1.23s
124:	learn: 0.7066250	total: 175ms	remaining: 1.22s
125:	learn: 0.7060798	total: 176ms	remaining: 1.22s
126:	learn: 0.7059257	total: 178ms	remaining: 1.22s
127:	learn: 0.7054002	total: 179ms	remaining: 1.22s
128:	learn: 0.7053150	total: 180ms	remaining: 1.22s
129:	learn: 0.7052352	total: 181ms	remaining: 1.21s
130:	learn: 0.7046034	total: 182ms	remaining: 1.21s
131:	learn: 0.7043090	total: 183ms	remaining: 1.21s
132:	learn: 0.7040099	total: 184ms	remaining: 1.2s
133:	learn: 0.7035345	total: 185ms	remaining: 1.2s
134:	learn: 0.7031207	total: 186ms	remaining: 1.19s
135:	learn: 0.7029582	total: 186ms	remaining: 1.18s
136:	learn: 0.7026255	total: 187ms	remaining: 1.18s
137:	learn: 0.7022481	total: 188ms	remaining: 1.18s
138:	learn: 0.7021403	total: 189ms	remaining: 1.17s
139:	learn: 0.7020817	total: 190ms	remaining: 1.17s
140:	learn: 0.7019362	total: 191ms	remaining: 1.16s
141:	learn: 0.7017881	total: 192ms	remaining: 1.16s
142:	learn: 0.7017276	total: 192ms	remaining: 1.15s
143:	learn: 0.7015506	total: 193ms	remaining: 1.15s
144:	learn: 0.7012758	total: 195ms	remaining: 1.15s
145:	learn: 0.7012284	total: 195ms	remaining: 1.14s
146:	learn: 0.7009479	total: 196ms	remaining: 1.14s
147:	learn: 0.7004005	total: 197ms	remaining: 1.13s
148:	learn: 0.7000471	total: 198ms	remaining: 1.13s
149:	learn: 0.6998084	total: 199ms	remaining: 1.13s
150:	learn: 0.6994226	total: 200ms	remaining: 1.12s
151:	learn: 0.6990901	total: 201ms	remaining: 1.12s
152:	learn: 0.6986686	total: 201ms	remaining: 1.11s
153:	learn: 0.6981233	total: 202ms	remaining: 1.11s
154:	learn: 0.6978907	total: 205ms	remaining: 1.11s
155:	learn: 0.6974978	total: 206ms	remaining: 1.11s
156:	learn: 0.6974408	total: 206ms	remaining: 1.11s
157:	learn: 0.6974131	total: 207ms	remaining: 1.1s
158:	learn: 0.6971277	total: 208ms	remaining: 1.1s
159:	learn: 0.6969713	total: 209ms	remaining: 1.1s
160:	learn: 0.6967325	total: 210ms	remaining: 1.09s
161:	learn: 0.6967320	total: 211ms	remaining: 1.09s
162:	learn: 0.6963896	total: 211ms	remaining: 1.08s
163:	learn: 0.6963449	total: 212ms	remaining: 1.08s
164:	learn: 0.6962530	total: 213ms	remaining: 1.08s
165:	learn: 0.6960646	total: 214ms	remaining: 1.07s
166:	learn: 0.6960642	total: 214ms	remaining: 1.07s
167:	learn: 0.6958550	total: 215ms	remaining: 1.06s
168:	learn: 0.6956587	total: 217ms	remaining: 1.06s
169:	learn: 0.6955162	total: 218ms	remaining: 1.06s
170:	learn: 0.6952058	total: 219ms	remaining: 1.06s
171:	learn: 0.6949965	total: 220ms	remaining: 1.06s
172:	learn: 0.6947669	total: 220ms	remaining: 1.05s
173:	learn: 0.6944307	total: 221ms	remaining: 1.05s
174:	learn: 0.6941898	total: 223ms	remaining: 1.05s
175:	learn: 0.6939011	total: 224ms	remaining: 1.05s
176:	learn: 0.6936224	total: 225ms	remaining: 1.04s
177:	learn: 0.6933596	total: 226ms	remaining: 1.04s
178:	learn: 0.6933499	total: 227ms	remaining: 1.04s
179:	learn: 0.6930267	total: 229ms	remaining: 1.04s
180:	learn: 0.6929618	total: 230ms	remaining: 1.04s
181:	learn: 0.6927253	total: 231ms	remaining: 1.04s
182:	learn: 0.6924862	total: 232ms	remaining: 1.03s
183:	learn: 0.6923640	total: 233ms	remaining: 1.03s
184:	learn: 0.6922288	total: 234ms	remaining: 1.03s
185:	learn: 0.6919219	total: 234ms	remaining: 1.02s
186:	learn: 0.6915565	total: 235ms	remaining: 1.02s
187:	learn: 0.6912400	total: 236ms	remaining: 1.02s
188:	learn: 0.6909883	total: 237ms	remaining: 1.02s
189:	learn: 0.6907535	total: 238ms	remaining: 1.01s
190:	learn: 0.6905610	total: 239ms	remaining: 1.01s
191:	learn: 0.6905433	total: 240ms	remaining: 1.01s
192:	learn: 0.6904132	total: 242ms	remaining: 1.01s
193:	learn: 0.6903875	total: 242ms	remaining: 1.01s
194:	learn: 0.6900019	total: 243ms	remaining: 1s
195:	learn: 0.6899605	total: 244ms	remaining: 1s
196:	learn: 0.6899090	total: 245ms	remaining: 997ms
197:	learn: 0.6896914	total: 246ms	remaining: 995ms
198:	learn: 0.6895238	total: 246ms	remaining: 992ms
199:	learn: 0.6893417	total: 247ms	remaining: 989ms
200:	learn: 0.6892128	total: 248ms	remaining: 986ms
201:	learn: 0.6890911	total: 249ms	remaining: 984ms
202:	learn: 0.6890319	total: 250ms	remaining: 981ms
203:	learn: 0.6889538	total: 251ms	remaining: 978ms
204:	learn: 0.6888027	total: 251ms	remaining: 975ms
205:	learn: 0.6885680	total: 252ms	remaining: 972ms
206:	learn: 0.6885636	total: 253ms	remaining: 969ms
207:	learn: 0.6885458	total: 254ms	remaining: 967ms
208:	learn: 0.6883133	total: 255ms	remaining: 965ms
209:	learn: 0.6881906	total: 256ms	remaining: 964ms
210:	learn: 0.6879723	total: 257ms	remaining: 961ms
211:	learn: 0.6878718	total: 258ms	remaining: 959ms
212:	learn: 0.6876534	total: 259ms	remaining: 957ms
213:	learn: 0.6875363	total: 260ms	remaining: 955ms
214:	learn: 0.6873582	total: 261ms	remaining: 952ms
215:	learn: 0.6871410	total: 262ms	remaining: 950ms
216:	learn: 0.6870013	total: 263ms	remaining: 949ms
217:	learn: 0.6869294	total: 264ms	remaining: 947ms
218:	learn: 0.6867528	total: 265ms	remaining: 944ms
219:	learn: 0.6867528	total: 265ms	remaining: 941ms
220:	learn: 0.6865951	total: 266ms	remaining: 939ms
221:	learn: 0.6863354	total: 268ms	remaining: 939ms
222:	learn: 0.6860609	total: 269ms	remaining: 937ms
223:	learn: 0.6859371	total: 270ms	remaining: 936ms
224:	learn: 0.6858646	total: 271ms	remaining: 933ms
225:	learn: 0.6857933	total: 272ms	remaining: 931ms
226:	learn: 0.6855883	total: 273ms	remaining: 929ms
227:	learn: 0.6853508	total: 274ms	remaining: 928ms
228:	learn: 0.6852000	total: 275ms	remaining: 925ms
229:	learn: 0.6851088	total: 276ms	remaining: 923ms
230:	learn: 0.6849508	total: 277ms	remaining: 922ms
231:	learn: 0.6847538	total: 278ms	remaining: 920ms
232:	learn: 0.6846558	total: 280ms	remaining: 921ms
233:	learn: 0.6845077	total: 281ms	remaining: 921ms
234:	learn: 0.6844011	total: 282ms	remaining: 919ms
235:	learn: 0.6841683	total: 283ms	remaining: 916ms
236:	learn: 0.6839887	total: 284ms	remaining: 914ms
237:	learn: 0.6838417	total: 285ms	remaining: 912ms
238:	learn: 0.6837238	total: 286ms	remaining: 910ms
239:	learn: 0.6836296	total: 287ms	remaining: 908ms
240:	learn: 0.6835638	total: 287ms	remaining: 905ms
241:	learn: 0.6834469	total: 288ms	remaining: 903ms
242:	learn: 0.6833500	total: 289ms	remaining: 901ms
243:	learn: 0.6832629	total: 290ms	remaining: 899ms
244:	learn: 0.6831572	total: 292ms	remaining: 899ms
245:	learn: 0.6830396	total: 295ms	remaining: 904ms
246:	learn: 0.6828226	total: 296ms	remaining: 903ms
247:	learn: 0.6827000	total: 297ms	remaining: 901ms
248:	learn: 0.6825957	total: 298ms	remaining: 899ms
249:	learn: 0.6824973	total: 299ms	remaining: 898ms
250:	learn: 0.6823910	total: 300ms	remaining: 896ms
251:	learn: 0.6823168	total: 301ms	remaining: 894ms
252:	learn: 0.6821883	total: 302ms	remaining: 892ms
253:	learn: 0.6820391	total: 303ms	remaining: 890ms
254:	learn: 0.6818642	total: 304ms	remaining: 888ms
255:	learn: 0.6817492	total: 305ms	remaining: 886ms
256:	learn: 0.6816371	total: 306ms	remaining: 886ms
257:	learn: 0.6815293	total: 308ms	remaining: 886ms
258:	learn: 0.6813541	total: 309ms	remaining: 884ms
259:	learn: 0.6812825	total: 310ms	remaining: 882ms
260:	learn: 0.6811603	total: 311ms	remaining: 880ms
261:	learn: 0.6810739	total: 312ms	remaining: 878ms
262:	learn: 0.6809159	total: 313ms	remaining: 876ms
263:	learn: 0.6808434	total: 314ms	remaining: 875ms
264:	learn: 0.6807340	total: 316ms	remaining: 877ms
265:	learn: 0.6806164	total: 318ms	remaining: 876ms
266:	learn: 0.6805532	total: 319ms	remaining: 875ms
267:	learn: 0.6804333	total: 320ms	remaining: 874ms
268:	learn: 0.6802970	total: 321ms	remaining: 873ms
269:	learn: 0.6802425	total: 322ms	remaining: 871ms
270:	learn: 0.6801936	total: 323ms	remaining: 870ms
271:	learn: 0.6801127	total: 324ms	remaining: 868ms
272:	learn: 0.6800208	total: 325ms	remaining: 866ms
273:	learn: 0.6799375	total: 326ms	remaining: 864ms
274:	learn: 0.6798326	total: 327ms	remaining: 862ms
275:	learn: 0.6797328	total: 328ms	remaining: 860ms
276:	learn: 0.6797041	total: 329ms	remaining: 858ms
277:	learn: 0.6796212	total: 330ms	remaining: 856ms
278:	learn: 0.6795690	total: 330ms	remaining: 854ms
279:	learn: 0.6794758	total: 331ms	remaining: 852ms
280:	learn: 0.6793951	total: 332ms	remaining: 850ms
281:	learn: 0.6793290	total: 334ms	remaining: 850ms
282:	learn: 0.6792613	total: 335ms	remaining: 848ms
283:	learn: 0.6791870	total: 336ms	remaining: 846ms
284:	learn: 0.6791164	total: 337ms	remaining: 845ms
285:	learn: 0.6790309	total: 338ms	remaining: 843ms
286:	learn: 0.6789729	total: 339ms	remaining: 841ms
287:	learn: 0.6788687	total: 339ms	remaining: 839ms
288:	learn: 0.6787982	total: 340ms	remaining: 837ms
289:	learn: 0.6787576	total: 341ms	remaining: 836ms
290:	learn: 0.6786716	total: 343ms	remaining: 835ms
291:	learn: 0.6786126	total: 344ms	remaining: 833ms
292:	learn: 0.6785671	total: 345ms	remaining: 832ms
293:	learn: 0.6784952	total: 346ms	remaining: 832ms
294:	learn: 0.6784374	total: 348ms	remaining: 831ms
295:	learn: 0.6783809	total: 349ms	remaining: 830ms
296:	learn: 0.6783214	total: 350ms	remaining: 828ms
297:	learn: 0.6782626	total: 351ms	remaining: 826ms
298:	learn: 0.6782199	total: 352ms	remaining: 824ms
299:	learn: 0.6781615	total: 352ms	remaining: 822ms
300:	learn: 0.6781171	total: 353ms	remaining: 820ms
301:	learn: 0.6780681	total: 354ms	remaining: 819ms
302:	learn: 0.6780218	total: 355ms	remaining: 817ms
303:	learn: 0.6779677	total: 356ms	remaining: 816ms
304:	learn: 0.6779311	total: 357ms	remaining: 814ms
305:	learn: 0.6778726	total: 358ms	remaining: 812ms
306:	learn: 0.6778512	total: 361ms	remaining: 814ms
307:	learn: 0.6777821	total: 362ms	remaining: 813ms
308:	learn: 0.6777085	total: 363ms	remaining: 812ms
309:	learn: 0.6776747	total: 364ms	remaining: 810ms
310:	learn: 0.6776278	total: 365ms	remaining: 809ms
311:	learn: 0.6775817	total: 366ms	remaining: 807ms
312:	learn: 0.6775076	total: 367ms	remaining: 806ms
313:	learn: 0.6774627	total: 368ms	remaining: 804ms
314:	learn: 0.6774236	total: 369ms	remaining: 803ms
315:	learn: 0.6773698	total: 370ms	remaining: 801ms
316:	learn: 0.6773327	total: 371ms	remaining: 800ms
317:	learn: 0.6772912	total: 372ms	remaining: 799ms
318:	learn: 0.6772454	total: 374ms	remaining: 798ms
319:	learn: 0.6772101	total: 375ms	remaining: 797ms
320:	learn: 0.6771819	total: 376ms	remaining: 795ms
321:	learn: 0.6771615	total: 377ms	remaining: 794ms
322:	learn: 0.6771242	total: 378ms	remaining: 792ms
323:	learn: 0.6770887	total: 379ms	remaining: 790ms
324:	learn: 0.6770518	total: 380ms	remaining: 789ms
325:	learn: 0.6769891	total: 381ms	remaining: 788ms
326:	learn: 0.6769687	total: 382ms	remaining: 786ms
327:	learn: 0.6769548	total: 383ms	remaining: 785ms
328:	learn: 0.6769309	total: 384ms	remaining: 783ms
329:	learn: 0.6768882	total: 385ms	remaining: 782ms
330:	learn: 0.6768557	total: 386ms	remaining: 781ms
331:	learn: 0.6768341	total: 388ms	remaining: 780ms
332:	learn: 0.6768199	total: 389ms	remaining: 779ms
333:	learn: 0.6767842	total: 390ms	remaining: 777ms
334:	learn: 0.6767539	total: 391ms	remaining: 776ms
335:	learn: 0.6767330	total: 392ms	remaining: 774ms
336:	learn: 0.6766798	total: 393ms	remaining: 773ms
337:	learn: 0.6766382	total: 394ms	remaining: 771ms
338:	learn: 0.6766008	total: 395ms	remaining: 769ms
339:	learn: 0.6765701	total: 396ms	remaining: 768ms
340:	learn: 0.6765193	total: 397ms	remaining: 767ms
341:	learn: 0.6764971	total: 398ms	remaining: 765ms
342:	learn: 0.6764764	total: 399ms	remaining: 764ms
343:	learn: 0.6764511	total: 400ms	remaining: 763ms
344:	learn: 0.6764143	total: 401ms	remaining: 762ms
345:	learn: 0.6763926	total: 402ms	remaining: 760ms
346:	learn: 0.6763670	total: 403ms	remaining: 759ms
347:	learn: 0.6763449	total: 404ms	remaining: 757ms
348:	learn: 0.6763286	total: 405ms	remaining: 756ms
349:	learn: 0.6762984	total: 406ms	remaining: 754ms
350:	learn: 0.6762538	total: 407ms	remaining: 753ms
351:	learn: 0.6762250	total: 408ms	remaining: 751ms
352:	learn: 0.6761886	total: 409ms	remaining: 749ms
353:	learn: 0.6761491	total: 410ms	remaining: 748ms
354:	learn: 0.6761244	total: 411ms	remaining: 746ms
355:	learn: 0.6760899	total: 412ms	remaining: 745ms
356:	learn: 0.6760570	total: 413ms	remaining: 745ms
357:	learn: 0.6760340	total: 414ms	remaining: 743ms
358:	learn: 0.6760142	total: 415ms	remaining: 741ms
359:	learn: 0.6760044	total: 416ms	remaining: 740ms
360:	learn: 0.6759863	total: 417ms	remaining: 739ms
361:	learn: 0.6759695	total: 418ms	remaining: 737ms
362:	learn: 0.6759478	total: 419ms	remaining: 735ms
363:	learn: 0.6759323	total: 420ms	remaining: 734ms
364:	learn: 0.6758976	total: 421ms	remaining: 732ms
365:	learn: 0.6758633	total: 422ms	remaining: 731ms
366:	learn: 0.6758348	total: 423ms	remaining: 729ms
367:	learn: 0.6758178	total: 424ms	remaining: 728ms
368:	learn: 0.6757844	total: 425ms	remaining: 726ms
369:	learn: 0.6757525	total: 426ms	remaining: 725ms
370:	learn: 0.6757317	total: 428ms	remaining: 725ms
371:	learn: 0.6757137	total: 428ms	remaining: 723ms
372:	learn: 0.6756934	total: 430ms	remaining: 722ms
373:	learn: 0.6756813	total: 431ms	remaining: 721ms
374:	learn: 0.6756714	total: 432ms	remaining: 719ms
375:	learn: 0.6756558	total: 433ms	remaining: 718ms
376:	learn: 0.6756438	total: 433ms	remaining: 716ms
377:	learn: 0.6756333	total: 435ms	remaining: 715ms
378:	learn: 0.6756186	total: 436ms	remaining: 714ms
379:	learn: 0.6756004	total: 437ms	remaining: 712ms
380:	learn: 0.6755782	total: 438ms	remaining: 711ms
381:	learn: 0.6755514	total: 439ms	remaining: 710ms
382:	learn: 0.6755427	total: 442ms	remaining: 712ms
383:	learn: 0.6755300	total: 444ms	remaining: 713ms
384:	learn: 0.6755075	total: 445ms	remaining: 711ms

In [327]:
from sklearn.linear_model import LinearRegression
pipe_lr = Pipeline([
    ('FeatureEngineering', FeatureEngineering()),
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])
pipe_lr.fit(X_train, y_train)
y_pred = pipe_lr.predict(X_test)
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print(r2)
print(mse)

0.12324352072192568
1.9011301208835794

In [19]:
from sklearn.tree import DecisionTreeRegressor
pipe_dt = Pipeline([
    ('FeatureEngineering', FeatureEngineering()),
    ('preprocessor', preprocessor),
    ('model', DecisionTreeRegressor(    
        random_state=42
    ))
])
pipe_dt.fit(X_train, y_train)
y_pred = pipe_dt.predict(X_test)
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(r2)
print(mse)
print(mae)

0.6187114845938375
0.8267735665694849
0.7137188208616779

In [330]:
import pickle

with open("clinic_model.pkl", "wb") as f:
    pickle.dump(pipe_dt, f)